#ifndef _FPIOA_DES_H
#define _FPIOA_DES_H
#define USABLE_FUNC_NUM 204
char* func_description[] = {
	"JTAG Test Clock"                       ,
	"JTAG Test Data In "                    ,
	"JTAG Test Mode Select "                ,
	"JTAG Test Data Out "                   ,
	"SPI0 Data 0"                           ,
	"SPI0 Data 1"                           ,
	"SPI0 Data 2"                           ,
	"SPI0 Data 3"                           ,
	"SPI0 Data 4"                           ,
	"SPI0 Data 5"                           ,
	"SPI0 Data 6"                           ,
	"SPI0 Data 7"                           ,
	"SPI0 Chip Select 0"                    ,
	"SPI0 Chip Select 1"                    ,
	"SPI0 Chip Select 2"                    ,
	"SPI0 Chip Select 3"                    ,
	"SPI0 Arbitration  "                    ,
	"SPI0 Serial Clock "                    ,
	"UART High speed Receiver "             ,
	"UART High speed Transmitter"           ,
	"Reserved function"                     ,
	"Reserved function"                     ,
	"Clock SPI1  "                          ,
	"Clock I2C1  "                          ,
	"GPIO High speed 0"                     ,
	"GPIO High speed 1"                     ,
	"GPIO High speed 2"                     ,
	"GPIO High speed 3"                     ,
	"GPIO High speed 4"                     ,
	"GPIO High speed 5"                     ,
	"GPIO High speed 6"                     ,
	"GPIO High speed 7"                     ,
	"GPIO High speed 8"                     ,
	"GPIO High speed 9"                     ,
	"GPIO High speed 10"                    ,
	"GPIO High speed 11"                    ,
	"GPIO High speed 12"                    ,
	"GPIO High speed 13"                    ,
	"GPIO High speed 14"                    ,
	"GPIO High speed 15"                    ,
	"GPIO High speed 16"                    ,
	"GPIO High speed 17"                    ,
	"GPIO High speed 18"                    ,
	"GPIO High speed 19"                    ,
	"GPIO High speed 20"                    ,
	"GPIO High speed 21"                    ,
	"GPIO High speed 22"                    ,
	"GPIO High speed 23"                    ,
	"GPIO High speed 24"                    ,
	"GPIO High speed 25"                    ,
	"GPIO High speed 26"                    ,
	"GPIO High speed 27"                    ,
	"GPIO High speed 28"                    ,
	"GPIO High speed 29"                    ,
	"GPIO High speed 30"                    ,
	"GPIO High speed 31"                    ,
	"GPIO pin 0"                            ,
	"GPIO pin 1"                            ,
	"GPIO pin 2"                            ,
	"GPIO pin 3"                            ,
	"GPIO pin 4"                            ,
	"GPIO pin 5"                            ,
	"GPIO pin 6"                            ,
	"GPIO pin 7"                            ,
	"UART1 Receiver"                        ,
	"UART1 Transmitter"                     ,
	"UART2 Receiver"                        ,
	"UART2 Transmitter"                     ,
	"UART3 Receiver "                       ,
	"UART3 Transmitter"                     ,
	"SPI1 Data 0"                           ,
	"SPI1 Data 1"                           ,
	"SPI1 Data 2"                           ,
	"SPI1 Data 3"                           ,
	"SPI1 Data 4"                           ,
	"SPI1 Data 5"                           ,
	"SPI1 Data 6"                           ,
	"SPI1 Data 7"                           ,
	"SPI1 Chip Select 0"                    ,
	"SPI1 Chip Select 1"                    ,
	"SPI1 Chip Select 2"                    ,
	"SPI1 Chip Select 3"                    ,
	"SPI1 Arbitration"                      ,
	"SPI1 Serial Clock"                     ,
	"SPI Slave Data 0"                      ,
	"SPI Slave Select"                      ,
	"SPI Slave Serial Clock "               ,
	"I2S0 Master Clock"                     ,
	"I2S0 Serial Clock(BCLK) "              ,
	"I2S0 Word Select(LRCLK) "              ,
	"I2S0 Serial Data Input 0 "             ,
	"I2S0 Serial Data Input 1 "             ,
	"I2S0 Serial Data Input 2 "             ,
	"I2S0 Serial Data Input 3 "             ,
	"I2S0 Serial Data Output 0"             ,
	"I2S0 Serial Data Output 1"             ,
	"I2S0 Serial Data Output 2"             ,
	"I2S0 Serial Data Output 3"             ,
	"I2S1 Master Clock"                     ,
	"I2S1 Serial Clock(BCLK)"               ,
	"I2S1 Word Select(LRCLK)"               ,
	"I2S1 Serial Data Input 0 "             ,
	"I2S1 Serial Data Input 1 "             ,
	"I2S1 Serial Data Input 2 "             ,
	"I2S1 Serial Data Input 3 "             ,
	"I2S1 Serial Data Output 0"             ,
	"I2S1 Serial Data Output 1"             ,
	"I2S1 Serial Data Output 2"             ,
	"I2S1 Serial Data Output 3"             ,
	"I2S2 Master Clock "                    ,
	"I2S2 Serial Clock(BCLK)"               ,
	"I2S2 Word Select(LRCLK)"               ,
	"I2S2 Serial Data Input 0 "             ,
	"I2S2 Serial Data Input 1 "             ,
	"I2S2 Serial Data Input 2 "             ,
	"I2S2 Serial Data Input 3 "             ,
	"I2S2 Serial Data Output 0"             ,
	"I2S2 Serial Data Output 1"             ,
	"I2S2 Serial Data Output 2"             ,
	"I2S2 Serial Data Output 3"             ,
	"Reserved function"                     ,
	"Reserved function"                     ,
	"Reserved function"                     ,
	"Reserved function"                     ,
	"Reserved function"                     ,
	"Reserved function"                     ,
	"I2C0 Serial Clock"                     ,
	"I2C0 Serial Data"                      ,
	"I2C1 Serial Clock"                     ,
	"I2C1 Serial Data"                      ,
	"I2C2 Serial Clock"                     ,
	"I2C2 Serial Data"                      ,
	"DVP System Clock"                      ,
	"DVP System Reset"                      ,
	"DVP Power Down Mode"                   ,
	"DVP Vertical Sync"                     ,
	"DVP Horizontal Reference output"       ,
	"Pixel Clock"                           ,
	"Data Bit 0"                            ,
	"Data Bit 1"                            ,
	"Data Bit 2"                            ,
	"Data Bit 3"                            ,
	"Data Bit 4"                            ,
	"Data Bit 5"                            ,
	"Data Bit 6"                            ,
	"Data Bit 7"                            ,
	"SCCB Serial Clock"                     ,
	"SCCB Serial Data"                      ,
	"UART1 Clear To Send"                   ,
	"UART1 Data Set Ready"                  ,
	"UART1 Data Carrier Detect"             ,
	"UART1 Ring Indicator"                  ,
	"UART1 Serial Infrared Input"           ,
	"UART1 Data Terminal Ready "            ,
	"UART1 Request To Send  "               ,
	"UART1 User-designated Output 2 "       ,
	"UART1 User-designated Output 1 "       ,
	"UART1 Serial Infrared Output"          ,
	"UART1 Transmit Clock Output "          ,
	"UART1 Receiver Output Enable"          ,
	"UART1 Driver Output Enable  "          ,
	"UART1 RS485 Enable"                    ,
	"UART2 Clear To Send "                  ,
	"UART2 Data Set Ready "                 ,
	"UART2 Data Carrier Detect "            ,
	"UART2 Ring Indicator"                  ,
	"UART2 Serial Infrared Input "          ,
	"UART2 Data Terminal Ready "            ,
	"UART2 Request To Send "                ,
	"UART2 User-designated Output 2"        ,
	"UART2 User-designated Output 1"        ,
	"UART2 Serial Infrared Output"          ,
	"UART2 Transmit Clock Output "          ,
	"UART2 Receiver Output Enable"          ,
	"UART2 Driver Output Enable  "          ,
	"UART2 RS485 Enable"                    ,
	"UART3 Clear To Send "                  ,
	"UART3 Data Set Ready"                  ,
	"UART3 Data Carrier Detect"             ,
	"UART3 Ring Indicator "                 ,
	"UART3 Serial Infrared Input"           ,
	"UART3 Data Terminal Ready "            ,
	"UART3 Request To Send "                ,
	"UART3 User-designated Output 2"        ,
	"UART3 User-designated Output 1"        ,
	"UART3 Serial Infrared Output"          ,
	"UART3 Transmit Clock Output"           ,
	"UART3 Receiver Output Enable"          ,
	"UART3 Driver Output Enable"            ,
	"UART3 RS485 Enable"                    ,
	"TIMER0 Toggle Output 1"                ,
	"TIMER0 Toggle Output 2"                ,
	"TIMER0 Toggle Output 3"                ,
	"TIMER0 Toggle Output 4"                ,
	"TIMER1 Toggle Output 1"                ,
	"TIMER1 Toggle Output 2"                ,
	"TIMER1 Toggle Output 3"                ,
	"TIMER1 Toggle Output 4"                ,
	"TIMER2 Toggle Output 1"                ,
	"TIMER2 Toggle Output 2"                ,
	"TIMER2 Toggle Output 3"                ,
	"TIMER2 Toggle Output 4"                ,
	"Clock SPI2"                            ,
	"Clock I2C2"                            ,
};
	
	
	
char* func_name[] = {	
	"JTAG_TCLK"             ,
	"JTAG_TDI"              ,
	"JTAG_TMS"              ,
	"JTAG_TDO"              ,
	"SPI0_D0"               ,
	"SPI0_D1"               ,
	"SPI0_D2"               ,
	"SPI0_D3"               ,
	"SPI0_D4"               ,
	"SPI0_D5"               ,
	"SPI0_D6"               ,
	"SPI0_D7"               ,
	"SPI0_SS0"              ,
	"SPI0_SS1"              ,
	"SPI0_SS2"              ,
	"SPI0_SS3"              ,
	"SPI0_ARB"              ,
	"SPI0_SCLK"             ,
	"UARTHS_RX"             ,
	"UARTHS_TX"             ,
	"RESV6"                 ,
	"RESV7"                 ,
	"CLK_SPI1 "             ,
	"CLK_I2C1 "             ,
	"GPIOHS0"               ,
	"GPIOHS1"               ,
	"GPIOHS2"               ,
	"GPIOHS3"               ,
	"GPIOHS4"               ,
	"GPIOHS5"               ,
	"GPIOHS6"               ,
	"GPIOHS7"               ,
	"GPIOHS8"               ,
	"GPIOHS9"               ,
	"GPIOHS10 "             ,
	"GPIOHS11 "             ,
	"GPIOHS12 "             ,
	"GPIOHS13 "             ,
	"GPIOHS14 "             ,
	"GPIOHS15 "             ,
	"GPIOHS16 "             ,
	"GPIOHS17 "             ,
	"GPIOHS18 "             ,
	"GPIOHS19 "             ,
	"GPIOHS20 "             ,
	"GPIOHS21 "             ,
	"GPIOHS22 "             ,
	"GPIOHS23 "             ,
	"GPIOHS24 "             ,
	"GPIOHS25 "             ,
	"GPIOHS26 "             ,
	"GPIOHS27 "             ,
	"GPIOHS28 "             ,
	"GPIOHS29 "             ,
	"GPIOHS30 "             ,
	"GPIOHS31 "             ,
	"GPIO0"                 ,
	"GPIO1"                 ,
	"GPIO2"                 ,
	"GPIO3"                 ,
	"GPIO4"                 ,
	"GPIO5"                 ,
	"GPIO6"                 ,
	"GPIO7"                 ,
	"UART1_RX "             ,
	"UART1_TX "             ,
	"UART2_RX "             ,
	"UART2_TX "             ,
	"UART3_RX "             ,
	"UART3_TX "             ,
	"SPI1_D0"               ,
	"SPI1_D1"               ,
	"SPI1_D2"               ,
	"SPI1_D3"               ,
	"SPI1_D4"               ,
	"SPI1_D5"               ,
	"SPI1_D6"               ,
	"SPI1_D7"               ,
	"SPI1_SS0 "             ,
	"SPI1_SS1 "             ,
	"SPI1_SS2 "             ,
	"SPI1_SS3 "             ,
	"SPI1_ARB "             ,
	"SPI1_SCLK"             ,
	"SPI_SLAVE_D0"          ,
	"SPI_SLAVE_SS"          ,
	"SPI_SLAVE_SCLK "       ,
	"I2S0_MCLK "            ,
	"I2S0_SCLK "            ,
	"I2S0_WS   "            ,
	"I2S0_IN_D0"            ,
	"I2S0_IN_D1"            ,
	"I2S0_IN_D2"            ,
	"I2S0_IN_D3"            ,
	"I2S0_OUT_D0"           ,
	"I2S0_OUT_D1"           ,
	"I2S0_OUT_D2"           ,
	"I2S0_OUT_D3"           ,
	"I2S1_MCLK"             ,
	"I2S1_SCLK"             ,
	"I2S1_WS  "             ,
	"I2S1_IN_D0 "           ,
	"I2S1_IN_D1 "           ,
	"I2S1_IN_D2 "           ,
	"I2S1_IN_D3 "           ,
	"I2S1_OUT_D0"           ,
	"I2S1_OUT_D1"           ,
	"I2S1_OUT_D2"           ,
	"I2S1_OUT_D3"           ,
	"I2S2_MCLK  "           ,
	"I2S2_SCLK  "           ,
	"I2S2_WS    "           ,
	"I2S2_IN_D0 "           ,
	"I2S2_IN_D1 "           ,
	"I2S2_IN_D2 "           ,
	"I2S2_IN_D3 "           ,
	"I2S2_OUT_D0"           ,
	"I2S2_OUT_D1"           ,
	"I2S2_OUT_D2"           ,
	"I2S2_OUT_D3"           ,
	"RESV0"                 ,
	"RESV1"                 ,
	"RESV2"                 ,
	"RESV3"                 ,
	"RESV4"                 ,
	"RESV5"                 ,
	"I2C0_SCLK"             ,
	"I2C0_SDA "             ,
	"I2C1_SCLK"             ,
	"I2C1_SDA "             ,
	"I2C2_SCLK"             ,
	"I2C2_SDA "             ,
	"CMOS_XCLK"             ,
	"CMOS_RST "             ,
	"CMOS_PWDN"             ,
	"CMOS_VSYNC "           ,
	"CMOS_HREF"             ,
	"CMOS_PCLK"             ,
	"CMOS_D0"               ,
	"CMOS_D1"               ,
	"CMOS_D2"               ,
	"CMOS_D3"               ,
	"CMOS_D4"               ,
	"CMOS_D5"               ,
	"CMOS_D6"               ,
	"CMOS_D7"               ,
	"SCCB_SCLK  "           ,
	"SCCB_SDA   "           ,
	"UART1_CTS  "           ,
	"UART1_DSR  "           ,
	"UART1_DCD  "           ,
	"UART1_RI   "           ,
	"UART1_SIR_IN   "       ,
	"UART1_DTR "            ,
	"UART1_RTS "            ,
	"UART1_OUT2"            ,
	"UART1_OUT1"            ,
	"UART1_SIR_OUT  "       ,
	"UART1_BAUD"            ,
	"UART1_RE  "            ,
	"UART1_DE  "            ,
	"UART1_RS485_EN "       ,
	"UART2_CTS"             ,
	"UART2_DSR"             ,
	"UART2_DCD"             ,
	"UART2_RI "             ,
	"UART2_SIR_IN "         ,
	"UART2_DTR "            ,
	"UART2_RTS "            ,
	"UART2_OUT2"            ,
	"UART2_OUT1"            ,
	"UART2_SIR_OUT "        ,
	"UART2_BAUD"            ,
	"UART2_RE "             ,
	"UART2_DE "             ,
	"UART2_RS485_EN"        ,
	"UART3_CTS"             ,
	"UART3_DSR"             ,
	"UART3_DCD"             ,
	"UART3_RI "             ,
	"UART3_SIR_IN "         ,
	"UART3_DTR "            ,
	"UART3_RTS "            ,
	"UART3_OUT2"            ,
	"UART3_OUT1"            ,
	"UART3_SIR_OUT"         ,
	"UART3_BAUD"            ,
	"UART3_RE"              ,
	"UART3_DE"              ,
	"UART3_RS485_EN "       ,
	"TIMER0_TOGGLE1 "       ,
	"TIMER0_TOGGLE2 "       ,
	"TIMER0_TOGGLE3 "       ,
	"TIMER0_TOGGLE4 "       ,
	"TIMER1_TOGGLE1 "       ,
	"TIMER1_TOGGLE2 "       ,
	"TIMER1_TOGGLE3 "       ,
	"TIMER1_TOGGLE4 "       ,
	"TIMER2_TOGGLE1 "       ,
	"TIMER2_TOGGLE2 "       ,
	"TIMER2_TOGGLE3 "       ,
	"TIMER2_TOGGLE4 "       ,
	"CLK_SPI2"              ,
	"CLK_I2C2"              ,
};	
#endif
