# Generated by Kconfiglib (https://github.com/ulfalizer/Kconfiglib)

#
# Toolchain configuration
#
CONFIG_TOOLCHAIN_PATH="/opt/kendryte-toolchain/bin"
CONFIG_TOOLCHAIN_PREFIX="riscv64-unknown-elf-"
# end of Toolchain configuration

#
# Components configuration
#

#
# Board config
#
# CONFIG_BOARD_MAIX is not set
CONFIG_BOARD_M5STICK=y
CONFIG_LCD_DEFAULT_WIDTH=240
CONFIG_LCD_DEFAULT_HEIGHT=135
CONFIG_LCD_DEFAULT_FREQ=40000000
CONFIG_SENSOR_FREQ=12000000
# end of Board config

CONFIG_COMPONENT_DRIVERS_ENABLE=y

#
# Drivers configuration
#

#
# SD card
#
CONFIG_SPI_SD_CARD_FORCE_HIGH_SPEED=y
# end of SD card
# end of Drivers configuration

CONFIG_COMPONENT_KENDRYTE_SDK_ENABLE=y

#
# Kendryte SDK configurations
#
CONFIG_SDK_LOG_LEVEL=5
# end of Kendryte SDK configurations

CONFIG_COMPONENT_MICROPYTHON_ENABLE=y

#
# Micropython configurations
#

#
# Modules configurations
#
CONFIG_MAIXPY_NES_ENABLE=y
CONFIG_MAIXPY_VIDEO_ENABLE=y
# CONFIG_MAIXPY_TOUCH_SCREEN_ENABLE is not set
# CONFIG_MAIXPY_OMV_MINIMUM is not set
CONFIG_MAIXPY_OMV_CONV_YUV_FAST=y
# CONFIG_MAIXPY_LVGL_ENABLE is not set
# end of Modules configurations

#
# Debug configurations
#
# CONFIG_MAIXPY_K210_UARTHS_DEBUG is not set
# end of Debug configurations
# end of Micropython configurations

CONFIG_COMPONENT_SPIFFS_ENABLE=y
CONFIG_COMPONENT_UTILS_ENABLE=y
# end of Components configuration
